### ISSUE TITLE
Client breaks when reset by server in local setup scenario.

### ISSUE THREAD

**Issue by mikevanis** [interactionresearchstudio/ESP32-SOCKETIO#53]
@davidchatting [this line](https://github.com/interactionresearchstudio/ESP32-SOCKETIO/blob/7ff73162eea03a46ff05004856305d1e7ce7a8f1/sockets_client.ino#L15) breaks the local setup currently. The client needs at least 4 seconds to scan through the wifis and make sure they're correct before resetting. Giving it a go with changing the delay to 4 seconds on the client side and leaving the captive portal reboot stuff as is.

**Comment by davidchatting** [comment]
can something be done with a state change watch rather than a delay?
