### ISSUE TITLE
Unable to access webui when built for ESP32S2

### ISSUE THREAD

**Issue by Babyyoda777** [interactionresearchstudio/ESP32-SOCKETIO#64]
Hi, I tried compiling the code for an ESP32-S2 dev board and it installed fine with the wifi networking showing up, however no capacitive portal pops up. Trying to manually visit 192.168.4.1 or 192.168.4.1/index.html returns a blank white screen on safari and just an error in chrome. Is there a problem specifically with the ESP32S2 or just an issue with the way the code is deploying the web page? Thanks, my fork is here: https://github.com/babyyoda777/ESP32-SOCKETIO/releases

I have uploaded the compiled binaries on here.

**Comment by Babyyoda777** [comment]
A wider problem I have found is that even building and installing original code directly the webserver doesnt work. It only works (even with correct esp32 board) when using firmware uploader

**Comment by mikevanis** [comment]
Are you trying to upload code with Arduino, or with the firmware uploader? If you're talking about uploading from Arduino, it sounds like you haven't uploaded the data folder. There are two steps to the upload process...

1. Upload code with regular "Upload" button
2. Upload data folder, which contains the website files for the captive portal. You do this with the ESP32 Sketch Data Upload tool. [Here's a tutorial](https://randomnerdtutorials.com/install-esp32-filesystem-uploader-arduino-ide/) that might help.

The firmware uploader sorts all that out for you, as it uploads a combined .bin file for the entire file system.

**Comment by mikevanis** [comment]
Additionally, we do not support ESP32-S2. You'll need to go on a bit of a journey to make sure the code works on it. Any particular reason why you want to use the S2?

**Comment by Babyyoda777** [comment]
Thanks I ended up getting it to work. My school accidentally bought 100 Esp32s2 boards and returning is a hassle. I believe he code works now, it connects to another board just need to check if lights function now
